name: Convert Developer ID Certificate
on:
  workflow_dispatch:
    inputs:
      certificate_password:
        description: 'Password to protect the final P12 certificate'
        required: true
        type: string
      certificate_base64:
        description: 'Base64 encoded .cer file'
        required: true
        type: string

jobs:
  convert-certificate:
    runs-on: macos-latest
    steps:
      - name: Create directories
        run: |
          mkdir -p certificate_input
          mkdir -p certificate_output
      
      - name: Write certificate file from input
        run: |
          echo "${{ github.event.inputs.certificate_base64 }}" | base64 --decode > certificate_input/certificate.cer