name: Create Developer ID Certificate
on:
  workflow_dispatch:

jobs:
  create-certificate:
    runs-on: macos-latest
    steps:
      - name: Create Certificate Signing Request
        run: |
          # Create directory to store files
          mkdir -p certificate_files
          
          # Create private key
          openssl genrsa -out certificate_files/private.key 2048
          
          # Create Certificate Signing Request (CSR)
          openssl req -new -key certificate_files/private.key -out certificate_files/CertificateSigningRequest.certSigningRequest \
            -subj "/emailAddress=${{ secrets.APPLE_ID }}/CN=Developer ID Application/C=US"
          
          # Create a password for encrypting the private key
          PRIVATE_KEY_PASSWORD=$(openssl rand -base64 24)
          echo "Created password for private key encryption: $PRIVATE_KEY_PASSWORD"
          echo "$PRIVATE_KEY_PASSWORD" > certificate_files/private_key_password.txt
          
          # Encrypt private key for safe storage
          openssl rsa -in certificate_files/private.key -out certificate_files/private.key.enc -aes256 -passout pass:"$PRIVATE_KEY_PASSWORD"
          
          # Create a README file with instructions
          cat > certificate_files/README.txt << 'EOL'
          CERTIFICATE SIGNING REQUEST INSTRUCTIONS:
          
          1. Upload the CertificateSigningRequest.certSigningRequest file to Apple Developer Portal
             - Go to https://developer.apple.com/account/resources/certificates/add
             - Select "Developer ID Application" certificate type
             - Upload this CSR file
          
          2. Download the .cer file from Apple Developer Portal
          
          3. Run the convert-developer-certificate workflow:
             - Upload the .cer file
             - Use the encrypted private key file (private.key.enc)
             - Use the password from private_key_password.txt
          EOL
          
          echo "Certificate files prepared successfully!"

      - name: Upload CSR file
        uses: actions/upload-artifact@v4
        with:
          name: certificate-signing-request
          path: certificate_files/CertificateSigningRequest.certSigningRequest
          
      - name: Upload encrypted private key and password
        uses: actions/upload-artifact@v4
        with:
          name: private-key-files
          path: |
            certificate_files/private.key.enc
            certificate_files/private_key_password.txt
            
      - name: Upload instructions
        uses: actions/upload-artifact@v4
        with:
          name: certificate-instructions
          path: certificate_files/README.txt