name: Set Up Apple Certificate
on:
  workflow_dispatch:

jobs:
  setup-certificate:
    runs-on: macos-latest
    steps:
      - name: Install Apple Certificate Tools
        run: |
          brew install openssl

      - name: Create Certificate
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # Create directory for certificates
          mkdir -p certs
          
          # Create private key
          openssl genrsa -out certs/private.key 2048
          
          # Create proper CSR
          openssl req -new -key certs/private.key -out certs/request.csr -subj "/CN=Developer ID Application: $APPLE_TEAM_ID/OU=$APPLE_TEAM_ID/O=Apple Development/C=US"
          
          # Create a strong password for P12
          export CERTIFICATE_PASSWORD=$(openssl rand -base64 24)
          echo "Using certificate password: $CERTIFICATE_PASSWORD"
          echo "CERTIFICATE_PASSWORD=$CERTIFICATE_PASSWORD" >> $GITHUB_ENV
          
          # For security, we'll print masked info
          echo "::add-mask::$CERTIFICATE_PASSWORD"
          
          # Create P12 certificate
          openssl pkcs12 -export -out certs/certificate.p12 -inkey certs/private.key -in certs/request.csr -passout pass:$CERTIFICATE_PASSWORD
          
          # Base64 encode the P12
          CERTIFICATE_BASE64=$(base64 -i certs/certificate.p12)
          echo "::add-mask::$CERTIFICATE_BASE64"
          
          # Output instructions for GitHub secrets
          echo ""
          echo "ADD THESE VALUES TO YOUR GITHUB SECRETS:"
          echo ""
          echo "APPLE_CERTIFICATE_PASSWORD: $CERTIFICATE_PASSWORD"
          echo ""
          echo "For APPLE_CERTIFICATE_BASE64, use this value (it's hidden in logs for security):"
          echo "$CERTIFICATE_BASE64"
